#!/usr/bin/env python3
"""Extracts fn-dsa's signing and sampler known-answer tests into plain-text fixtures.

Sources (Thomas Pornin, The Unlicense), commit 0629bb1, identical in crates.io 0.4.0:
  fn-dsa-sign/src/lib.rs:784-1151     sign_512: KAT_512_SK, _VK, _MU, _SIGN_SEED,
                                      _SIGN_SEED_DERIVED, _SIG (test S-PAR-2)
  fn-dsa-sign/src/sampler.rs:646-2816 sampler: KAT_SAMPLER_512_SEED, _NONCE, _MU, _INVSIGMA,
                                      _OUT (test S-SAMP-1)

FLR::scaled(x, sc) is x * 2^sc, exact in binary64 (|x| < 2^53); the fixtures store the IEEE
bit patterns in hex.

Usage:
  python3 tools/sign/extract_fndsa_kats.py <fn-dsa-sign/src directory> tests/fixtures/sign
"""
import os
import re
import struct
import sys


def u8_array(src, name):
    m = re.search(r"const %s: \[u8; (\d+)\] = \[(.*?)\];" % name, src, re.S)
    vals = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(2))]
    assert len(vals) == int(m.group(1)), name
    return bytes(vals)


def flr_array(src, name):
    m = re.search(r"const %s: \[FLR; (\d+)\] = \[(.*?)\];" % name, src, re.S)
    out = []
    for x, a, b in re.findall(r"FLR::scaled\(\s*(-?0x[0-9A-Fa-f]+),\s*(-?\d+)\s*([+-]\s*\d+)?\)",
                              m.group(2)):
        sc = int(a) + (int(b.replace(" ", "")) if b else 0)
        xi = int(x, 16)
        assert abs(xi) < 2**53
        out.append(float(xi) * 2.0**sc)
    assert len(out) == int(m.group(1)), name
    return out


def i16_array(src, name):
    m = re.search(r"const %s: \[i16; (\d+)\] = \[(.*?)\];" % name, src, re.S)
    vals = [int(v) for v in re.findall(r"-?\d+", m.group(2))]
    assert len(vals) == int(m.group(1)), name
    return vals


def bits(x):
    return "%016x" % struct.unpack("<Q", struct.pack("<d", x))[0]


def main():
    srcdir, outdir = sys.argv[1], sys.argv[2]
    lib = open(os.path.join(srcdir, "lib.rs")).read()
    samp = open(os.path.join(srcdir, "sampler.rs")).read()
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "fndsa_sign512_kat.txt"), "w") as fh:
        fh.write("# fn-dsa-sign/src/lib.rs:784-1151 (sign_512), commit 0629bb1; "
                 "generated by tools/sign/extract_fndsa_kats.py\n")
        for key, name in [("sk", "KAT_512_SK"), ("vk", "KAT_512_VK"), ("mu", "KAT_512_MU"),
                          ("seed", "KAT_512_SIGN_SEED"),
                          ("seed_derived", "KAT_512_SIGN_SEED_DERIVED"), ("sig", "KAT_512_SIG")]:
            fh.write("%s %s\n" % (key, u8_array(lib, name).hex()))
    seed = u8_array(samp, "KAT_SAMPLER_512_SEED")
    nonce = u8_array(samp, "KAT_SAMPLER_512_NONCE")
    mu = flr_array(samp, "KAT_SAMPLER_512_MU")
    isig = flr_array(samp, "KAT_SAMPLER_512_INVSIGMA")
    out = i16_array(samp, "KAT_SAMPLER_512_OUT")
    assert len(mu) == len(isig) == len(out) == 1024
    with open(os.path.join(outdir, "fndsa_sampler512_kat.txt"), "w") as fh:
        fh.write("# fn-dsa-sign/src/sampler.rs:646-2816 (sampler), commit 0629bb1; "
                 "generated by tools/sign/extract_fndsa_kats.py\n")
        fh.write("# seed, nonce, then per draw: mu (f64 bits), 1/sigma (f64 bits), output\n")
        fh.write("seed %s\n" % seed.hex())
        fh.write("nonce %s\n" % nonce.hex())
        for a, b, c in zip(mu, isig, out):
            fh.write("%s %s %d\n" % (bits(a), bits(b), c))


if __name__ == "__main__":
    main()
