#!/usr/bin/env python3
"""Writes src/fft/gm.rs: fn-dsa's FFT twiddle table GM as IEEE-754 bit patterns.

Source: fn-dsa-sign/src/poly.rs:1577-2602 (Thomas Pornin, The Unlicense), commit 0629bb1
(identical in crates.io fn-dsa-sign 0.4.0). Each entry is FLR::ZERO, FLR::NZERO, FLR::ONE or
mkflr(x, sc) = x * 2^sc, which is exact in binary64 (|x| < 2^53). The script also checks
fn-dsa's own digest of the table (check_GM, poly.rs:2694-2706):
SHAKE256(little-endian encodings) = f45a496c...0af1e.

Usage: python3 tools/sign/gen_gm.py <path to fn-dsa-sign/src/poly.rs> > src/fft/gm.rs
"""
import hashlib
import re
import struct
import sys

DIGEST = "f45a496cf56ccc6e3e3395a20209206d81d71a7905a661447bd5bc0e24e0af1e"


def main():
    src = open(sys.argv[1]).read()
    body = re.search(r"pub\(crate\) const GM: \[FLR; 2048\] = \[(.*?)\];", src, re.S).group(1)
    toks = re.findall(r"FLR::ZERO|FLR::NZERO|FLR::ONE|mkflr\(\s*(-?\d+),\s*(-?\d+)\)", body)
    vals = []
    for m in re.finditer(r"FLR::ZERO|FLR::NZERO|FLR::ONE|mkflr\(\s*(-?\d+),\s*(-?\d+)\)", body):
        t = m.group(0)
        if t == "FLR::ZERO":
            vals.append(0.0)
        elif t == "FLR::NZERO":
            vals.append(-0.0)
        elif t == "FLR::ONE":
            vals.append(1.0)
        else:
            x, sc = int(m.group(1)), int(m.group(2))
            assert abs(x) < 2**53
            vals.append(float(x) * 2.0**sc)  # exact: power-of-two scaling
    assert len(vals) == 2048, len(vals)
    enc = b"".join(struct.pack("<d", v) for v in vals)
    dig = hashlib.shake_256(enc).hexdigest(32)
    assert dig == DIGEST, dig
    out = []
    out.append("//! fn-dsa's FFT twiddle table `GM`, as IEEE-754 binary64 bit patterns.")
    out.append("//!")
    out.append("//! Generated by `tools/sign/gen_gm.py` from fn-dsa-sign/src/poly.rs:1577-2602 (Thomas Pornin,")
    out.append("//! The Unlicense), commit 0629bb1; do not edit by hand. For k = 1..1023 and j = rev10(k):")
    out.append("//! `GM[2k] = cos(j*pi/1024)`, `GM[2k+1] = sin(j*pi/1024)`, correctly rounded; `GM[0..2]` is")
    out.append("//! unused. SHAKE256 of the little-endian encodings is fn-dsa's `check_GM` digest")
    out.append(f"//! `{DIGEST}`")
    out.append("//! (checked by the generator and by the test `fft::tests::gm_digest`).")
    out.append("")
    out.append("/// The twiddle factors (see the module documentation).")
    out.append("#[rustfmt::skip]")
    out.append("pub(crate) const GM: [f64; 2048] = [")
    for i in range(0, 2048, 2):
        a, b = (struct.unpack("<Q", struct.pack("<d", v))[0] for v in vals[i:i + 2])
        out.append(f"    f64::from_bits(0x{a:016x}), f64::from_bits(0x{b:016x}),")
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main()
