//! The dense sublattice of generated keys (docs/security.md, "Key distribution").
//!
//! For keys from `trapgen`, prints the ratios `vol(R(g, -f))^(1/d) / sqrt(q)` and
//! `||(g, f)|| / sqrt(q)`, and checks the window `[1/1.17, 1.17]` that Falcon's two norm tests
//! imply for both. `R(g, -f)` is the sublattice of `{(s0, s1) : s0 + h s1 = 0 mod q}` generated by
//! the key. With `s_j = |f(z_j)|^2 + |g(z_j)|^2` at the `d` roots `z_j` of `x^d + 1`,
//! `vol(R(g, -f))^2 = prod_j s_j`, `||(g, f)||^2 = (1/d) sum_j s_j`, and Falcon's second squared
//! Gram-Schmidt norm is `(q^2/d) sum_j 1/s_j`; the `s_j` are evaluated by a direct DFT, independent
//! of the crate's FFT.
//!
//! Key `i` uses the seed `LE64(i) || 24 bytes 0x5A`.
//!
//! Usage: `cargo run --release --example stats_density [count] [pcs|falcon1024]`
//! (default: 2000 keys at the PCS set).

use ntru_trapdoor::{Params, trapgen};
use std::f64::consts::PI;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let count: u64 = match args.get(1) {
        None => 2000,
        Some(s) => s
            .parse()
            .unwrap_or_else(|_| panic!("count must be a number, got {s}")),
    };
    let params = match args.get(2).map(String::as_str) {
        None | Some("pcs") => Params::PCS,
        Some("falcon1024") => Params::FALCON_1024,
        Some(other) => panic!("unknown parameter set {other}; use pcs or falcon1024"),
    };
    let d = params.n();
    let q = f64::from(params.q);
    // cos and sin of pi m / d, m < 2d: z_j^k = exp(i pi (2j+1) k / d).
    let (cos, sin): (Vec<f64>, Vec<f64>) = (0..2 * d)
        .map(|m| {
            let a = PI * m as f64 / d as f64;
            (a.cos(), a.sin())
        })
        .unzip();
    let eval = |p: &[i16], j: usize| -> (f64, f64) {
        let (mut re, mut im) = (0.0, 0.0);
        for (k, &c) in p.iter().enumerate() {
            let m = ((2 * j + 1) * k) % (2 * d);
            re += f64::from(c) * cos[m];
            im += f64::from(c) * sin[m];
        }
        (re, im)
    };
    let bound = 1.17f64;
    let (mut vmin, mut vmax, mut vsum) = (f64::INFINITY, 0.0f64, 0.0f64);
    let (mut nmin, mut nmax, mut nsum) = (f64::INFINITY, 0.0f64, 0.0f64);
    for i in 0..count {
        let mut seed = [0x5Au8; 32];
        seed[..8].copy_from_slice(&i.to_le_bytes());
        let (_pk, sk) = trapgen(&params, &seed).expect("trapgen");
        let (f, g) = (sk.f(), sk.g());
        // The d roots come in d/2 conjugate pairs; each pair has one s_j.
        let (mut ln_prod, mut sum, mut inv_sum) = (0.0, 0.0, 0.0);
        for j in 0..d / 2 {
            let (fr, fi) = eval(f, j);
            let (gr, gi) = eval(g, j);
            let s = fr * fr + fi * fi + gr * gr + gi * gi;
            ln_prod += 2.0 * s.ln();
            sum += 2.0 * s;
            inv_sum += 2.0 / s;
        }
        let n1: i64 = f
            .iter()
            .chain(g)
            .map(|&x| i64::from(x) * i64::from(x))
            .sum();
        let n1 = n1 as f64;
        assert!(
            (sum / d as f64 - n1).abs() <= 1e-9 * n1,
            "key {i}: Parseval"
        );
        let n2 = q * q / d as f64 * inv_sum;
        let tol = 1e-9;
        assert!(
            n1 <= bound * bound * q && n2 <= bound * bound * q * (1.0 + tol),
            "key {i}: norm tests"
        );
        let vol = (0.5 * ln_prod / d as f64).exp() / q.sqrt();
        let norm = n1.sqrt() / q.sqrt();
        // AM-GM: vol^(1/d) <= ||(g,f)|| <= 1.17 sqrt q, and q^2 / vol^(2/d) <= N2 <= 1.17^2 q.
        assert!(
            vol >= (1.0 - tol) / bound && vol <= norm * (1.0 + tol) && norm <= bound,
            "key {i}: window"
        );
        (vmin, vmax, vsum) = (vmin.min(vol), vmax.max(vol), vsum + vol);
        (nmin, nmax, nsum) = (nmin.min(norm), nmax.max(norm), nsum + norm);
    }
    let c = count as f64;
    println!("{}: {count} keys (seeds LE64(i) || 0x5A^24)", params.name);
    println!(
        "vol(R(g,-f))^(1/d) / sqrt(q): min {vmin:.4}  mean {:.4}  max {vmax:.4}",
        vsum / c
    );
    println!(
        "||(g,f)|| / sqrt(q):          min {nmin:.4}  mean {:.4}  max {nmax:.4}",
        nsum / c
    );
    println!(
        "window implied by the norm tests: [{:.4}, {:.4}] for both; every key checked",
        1.0 / bound,
        bound
    );
}
