#!/usr/bin/env python3
"""Extracts fn-dsa's verification known-answer tests into a plain-text fixture.

Source (Thomas Pornin, The Unlicense), commit 0629bb1, identical in crates.io 0.4.0:
  fn-dsa-vrfy/src/lib.rs:389-914   verify_kat_512, verify_kat_1024: KAT_512_VK, KAT_512_MU,
                                   KAT_512_SIG, KAT_1024_VK, KAT_1024_MU, KAT_1024_SIG

fn-dsa verifies each signature twice (lib.rs:398-401): with HASH_ID_EXTMU and the stored mu,
and with DomainContext(b"context"), HASH_ID_RAW and the message b"message"; the stored mu is
compute_mu(hash(vk), b"context", HASH_ID_RAW, b"message"). Used by tests/parity_fndsa_diff.rs
(P-VKAT).

Usage:
  python3 tools/parity/extract_fndsa_vrfy_kats.py <fn-dsa-vrfy/src directory> tests/fixtures/parity
"""
import os
import re
import sys


def u8_array(src, name):
    m = re.search(r"const %s: \[u8; (\d+)\] = \[(.*?)\];" % name, src, re.S)
    vals = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{2})", m.group(2))]
    assert len(vals) == int(m.group(1)), name
    return bytes(vals)


def main():
    srcdir, outdir = sys.argv[1], sys.argv[2]
    lib = open(os.path.join(srcdir, "lib.rs")).read()
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, "fndsa_vrfy_kat.txt"), "w") as fh:
        fh.write("# fn-dsa-vrfy/src/lib.rs:389-914 (verify_kat_512, verify_kat_1024), commit 0629bb1; "
                 "generated by tools/parity/extract_fndsa_vrfy_kats.py\n")
        for logn, deg in [(9, 512), (10, 1024)]:
            vk = u8_array(lib, "KAT_%d_VK" % deg)
            mu = u8_array(lib, "KAT_%d_MU" % deg)
            sig = u8_array(lib, "KAT_%d_SIG" % deg)
            assert vk[0] == logn and sig[0] == 0x30 + logn and len(mu) == 64
            fh.write("vk%d %s\n" % (deg, vk.hex()))
            fh.write("mu%d %s\n" % (deg, mu.hex()))
            fh.write("sig%d %s\n" % (deg, sig.hex()))


if __name__ == "__main__":
    main()
